#!/bin/bash
# ------------------------------------------------------------
#  prepare-photos.sh  (macOS, nothing to install)
#
#  Resizes your original photos for the web, makes thumbnails,
#  and updates the photo list the site reads (photos.js).
#
#  Usage:   ./prepare-photos.sh  /path/to/folder/of/originals
#
#  Your originals are never changed. Safe to run again whenever
#  you add more photos: only new ones get processed.
# ------------------------------------------------------------
set -euo pipefail

SRC="${1:-}"
if [[ -z "$SRC" || ! -d "$SRC" ]]; then
  echo "Usage: ./prepare-photos.sh /path/to/folder/of/originals"
  exit 1
fi

SITE="$(cd "$(dirname "$0")" && pwd)"
FULL="$SITE/photos/full"
THUMBS="$SITE/photos/thumbs"
mkdir -p "$FULL" "$THUMBS"

FULL_SIZE=2048   # longest edge, in pixels
THUMB_SIZE=800
QUALITY=82       # JPEG quality, 0-100

# Remove the stand-in photos the first time real ones are added
rm -f "$FULL"/standin-*.jpg "$THUMBS"/standin-*.jpg

shopt -s nullglob nocaseglob
added=0
for f in "$SRC"/*.{jpg,jpeg,png,heic,heif,tif,tiff,webp}; do
  base="$(basename "$f")"
  stem="${base%.*}"
  # web-safe file name: spaces and odd characters become dashes
  safe="$(printf '%s' "$stem" | tr -cs 'A-Za-z0-9._-' '-' | sed 's/^-*//; s/-*$//')"
  out="$safe.jpg"

  if [[ -f "$FULL/$out" && "$FULL/$out" -nt "$f" ]]; then
    continue  # already done
  fi

  echo "  $base  ->  $out"
  sips -s format jpeg -s formatOptions "$QUALITY" -Z "$FULL_SIZE" "$f" --out "$FULL/$out" >/dev/null
  sips -s format jpeg -s formatOptions 70 -Z "$THUMB_SIZE" "$FULL/$out" --out "$THUMBS/$out" >/dev/null
  added=$((added + 1))
done
shopt -u nocaseglob

# Rebuild the photo list from everything in photos/full
{
  echo "// Generated by prepare-photos.sh. Don't edit by hand."
  echo "window.PHOTOS = ["
  for p in "$FULL"/*.jpg; do
    name="$(basename "$p")"
    [[ -f "$THUMBS/$name" ]] || continue
    printf '  "%s",\n' "${name//\"/\\\"}"
  done
  echo "];"
} > "$SITE/photos.js"

total=$(grep -c '^  "' "$SITE/photos.js" || true)
size=$(du -sh "$SITE/photos" | cut -f1)
echo ""
echo "Done: $added new photo(s) processed, $total total, photos folder is $size."
